.PHONY: start stop restart status deploy post

start:
	@./deploy/scripts/orchestrate.sh start

stop:
	@./deploy/scripts/orchestrate.sh stop

restart:
	@./deploy/scripts/orchestrate.sh restart

status:
	@./deploy/scripts/orchestrate.sh status

deploy:
	@./deploy/scripts/deploy.sh

post:
	@./deploy/scripts/post.sh
